
CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  address VARCHAR(50) NOT NULL,
  email VARCHAR(30) DEFAULT NULL
);


